# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [3]:
l = [1,2,3,4,5]
a = np.array(l)
a

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [4]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(l1)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [5]:
arr = np.arange(1,18,2)
arr.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [9]:
np.random.randint(0,10,10)

array([2, 8, 0, 1, 7, 3, 3, 4, 8, 5])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [23]:
arr1 = np.array([1,2,3,4,5])
arr1 = arr1.reshape(5,1)
arr1

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [24]:
arr1.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [39]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2[[2,3,8]])

[3 4 9]


Print alternate elements of that array

In [40]:
arr2[::2]

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

In [42]:
arr2[-3:] = 100
arr2

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [44]:
arr3 = np.random.randint(0,50,25)
arr3 = arr3.reshape(5,5)
arr3

array([[28, 16, 11, 44, 39],
       [24, 14,  0,  6, 46],
       [27,  6, 38, 21, 43],
       [22,  2, 30, 14,  8],
       [23, 46, 27,  7, 32]])

In [46]:
# to print middle(3*3) matrix
arr3[1:-1,1:-1]

array([[14,  0,  6],
       [ 6, 38, 21],
       [ 2, 30, 14]])